version: 0.2
env:
  variables:
    GOOS: "darwin"
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - make -f lab_01/Makefile
artifacts:
  files:
    - hello.exe
