version: 0.2
env:
  parameter-store:
    GOOS: "/codebuild-nht/goos"
#  variables:
#    GOOS: "darwin"
phases:
  pre_build:
    commands:
      - env
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - make -f lab_01/Makefile
artifacts:
  files:
    - hello
